require_destination: true

service: unified-flash-messages

image: <%= ENV.fetch('DEPLOY_IMAGE') %>

servers:
  web:
    hosts:
<% ENV.fetch('DEPLOY_SERVERS_WEB_HOSTS').split(',').each do |host| %>
      - <%= host.strip %>
<% end %>

proxy:
  host: <%= ENV.fetch('DEPLOY_PROXY_HOST') %>
  app_port: <%= ENV.fetch('DEPLOY_THRUSTER_HTTP_PORT') %>
<% if ENV['DEPLOY_PROXY_BUFFERING_MAX_REQUEST_BODY'].present? %>
  buffering:
    requests: true
    responses: true
    max_request_body: <%= ENV['DEPLOY_PROXY_BUFFERING_MAX_REQUEST_BODY'] %>
    max_response_body: 0
<% end %>

registry:
  server: <%= ENV.fetch('DEPLOY_REGISTRY_SERVER') %>
  username: <%= ENV.fetch('DEPLOY_REGISTRY_USERNAME') %>
  password:
    - DEPLOY_REGISTRY_PASSWORD

builder:
  arch:
    - amd64
    - arm64
  context: .
  dockerfile: Dockerfile
  args:
    THRUSTER_HTTP_PORT: <%= ENV.fetch('DEPLOY_THRUSTER_HTTP_PORT', 3001) %>
    THRUSTER_TARGET_PORT: <%= ENV.fetch('DEPLOY_THRUSTER_TARGET_PORT', 3000) %>

env:
  secret:
    - SECRET_KEY_BASE

ssh:
  port: <%= ENV.fetch('DEPLOY_SSH_PORT', 22) %>
  user: <%= ENV.fetch('DEPLOY_SSH_USER') %>
  keys_only: true
  keys:
<% ENV.fetch('DEPLOY_SSH_KEYS').split(',').each do |key| %>
    - <%= key.strip %>
<% end %>
